### ISSUE TITLE
IRQ problems with libopencm3-examples and Luftboot on Lisa/M v2

### ISSUE THREAD

**Issue by doniec** [libopencm3/libopencm3-examples#10]
BACKGROUND:
I have a Lisa/M v2 board with the Aspirin v2.2 10DoM imu on it.
I use mac osx 10.8.4, and installed the newest version of paparazzi tools with macports, the gnu chain I have is:

gcc version 4.7.3 20121207 (release) [ARM/embedded-4_7-branch revision 194305] (GNU Tools for ARM Embedded Processors)

I use a BMP to upload my code.

NOW TO THE ISSUE:

When I compile examples/stm/f1/lisa-m-2/usart_printf and upload it everything works as it should (I can see the text output on the usart).

When I compiled examples/stm/f1/lisa-m-2/usart_irq_printf and upload it nothing happens, no usart output at least. By adding led signals into the code I can see that the execution stops behaving as it should right after systick_counter_enable(); is called and I believe when the first interrupt occurs.

I tried this issue on two Lisa/M v2 boards, one factory-flashed, one flashed by myself with Luftboot about a month ago.

I also tried on a Ubuntu machine with the newest version of paparazzi and the gcc toolchain that came with it, same result.

**Comment by karlp** [comment]
Totally unreproduceable, no further information from the submitter. closing.
