### ISSUE TITLE
readability of the external interrupt code

### ISSUE THREAD

**Issue by Virtex7** [libopencm3/libopencm3-examples#100]
because of the mass of #defines (DISCO_) you have to read the sysconfig.h and the main.c at the same time. to understand the use of the external Interrupt it would be better to write the direct name in the librarys functions..

or just some comments on the interrupt functions...

**Comment by karlp** [comment]
Yes.  Some of the examples use that style to make them easier to port between boards.  It's only a single header and a single main.  I'm not sure how much could be done here.
