### ISSUE TITLE
lsusb shows this codes device as STM32F407?

### ISSUE THREAD

**Issue by lloyd-g** [libopencm3/libopencm3-examples#108]
libopencm3-examples / examples / stm32 / f1 / stm32-h103 / usb_cdcacm 
is the device name string from libopencm3?
and is there a way to make windows recognise this device.
it knows it is a cdcacm device but can't find a driver?
maybe it's the device name?

**Comment by karlp** [comment]
lsusb uses a static list, based on vid/pid.  See https://github.com/libopencm3/libopencm3-examples/blob/master/examples/stm32/f1/stm32-h103/usb_cdcacm/cdcacm.c#L34-L35

libopencm3 doens't have a vendor id, nor any product ids it has any rights to.  As for windows, you'll need to take it up there what you need for what drivers to be recognised. it's not something we have any control over.
