### ISSUE TITLE
Maple miniblink enables clock for GPIO C, then uses GPIO A, doesn't blink.

### ISSUE THREAD

**Issue by realblades** [libopencm3/libopencm3-examples#117]
https://github.com/libopencm3/libopencm3-examples/blob/master/examples/stm32/f1/stm32-maple/miniblink/miniblink.c

I sed this as a test hello with a Maple Mini clone and got no output. I looked at the code and noticed that it does `rcc_periph_clock_enable(RCC_GPIOC);` and then wiggles `GPIOA5`. Changing the enable to `RCC_GPIOA` made the pin "blink".

There is no led on that pin on Maple, but that may or may not be the intended outcome.

**Comment by karlp** [comment]
Fixed to work on the original "maple" board, which has the led on A5.  your maple mini has a different led pin unfortunately.
