### ISSUE TITLE
stm32f107/207 usbd_init hangs when RCC_OTGFS clock is not enabled

### ISSUE THREAD

**Issue by progzmaster** [libopencm3/libopencm3-examples#138]
Hello!

In lib/usb/usb_f107 (and also in lib/usb/usb_f207) there are 2 while loops, and the "Wait for AHB idle" one never exits if the OTG clock is disabled. A little bit hard to understand (at least for a beginner) why the system hangs. I recommend usiing some timeout method, and returning an error code indicating that the initilazation was unsuccessful.

```
static usbd_device *stm32f107_usbd_init(void)
{
OTG_FS_GINTSTS = OTG_GINTSTS_MMIS;

OTG_FS_GUSBCFG |= OTG_GUSBCFG_PHYSEL;
/* Enable VBUS sensing in device mode and power down the PHY. */
OTG_FS_GCCFG |= OTG_GCCFG_VBUSBSEN | OTG_GCCFG_PWRDWN;

/* Wait for AHB idle. */
while (!(OTG_FS_GRSTCTL & OTG_GRSTCTL_AHBIDL));
/* Do core soft reset. */
OTG_FS_GRSTCTL |= OTG_GRSTCTL_CSRST;
while (OTG_FS_GRSTCTL & OTG_GRSTCTL_CSRST);
```

**Comment by karlp** [comment]
indeed.  fixed (though not the way you were asking for) in https://github.com/libopencm3/libopencm3/pull/705
