### ISSUE TITLE
stm32f4-discovery/usb_msc doesn't work

### ISSUE THREAD

**Issue by rgwan** [libopencm3/libopencm3-examples#150]
It can be recognized by Linux, and you also can read any sector you want.

But you can't write, if you write, the kernel unloads this device and report I/O error.

**Comment by karlp** [comment]
works as intended...

Did you actually look at the code? https://github.com/libopencm3/libopencm3-examples/blob/master/examples/stm32/f4/stm32f4-discovery/usb_msc/ramdisk.c#L169-L175
