### ISSUE TITLE
stm32f1-h103 usb examples not working

### ISSUE THREAD

**Issue by ravenland** [libopencm3/libopencm3-examples#184]
Hello everyone,
    I've just tried to test the usb examples for the stm32-h103 board and none of them enumerate. Other examples seem to work fine, can anyone else confirm?

Best regards.

**Comment by karlp** [comment]
I'm afraid I don't have that board.  I highly recommend the tests/gadget-zero code for demonstrating usb functionality, the usb examples in this repo are a soup of copy/paste and have had zero regression testing.

**Comment by ravenland** [comment]
Hi @karlp , thank you for the suggestions. The oscillator was my first guess and I tried that, I also tried a couple of things with PORTC11, I'll try again this weekend and report back here.

**Comment by ravenland** [comment]
Using HSE and doing the PORTC11 dance, the device still ends up failing enumeration. when connected to a host it ends up in a hard fault, looping in blocking handler. Any idea what may cause this?

**Comment by ravenland** [comment]
Here's the relevant code https://pastecode.xyz/view/6c99a8ae, everything else is unchanged. Gadget 0 exhibits the same behavior.

**Comment by karlp** [comment]
are you sure your hw actually works? are you perhaps using a linker script with the wrong amount of ram specified?

**Comment by ravenland** [comment]
:) I hope the hw works. Linker script is ok. I suspect that something happens when the host tries to read the descriptor, will look further into it.

**Comment by karlp** [comment]
I'm just saying that the gadget0 code for example works on _many_ platforms and hosts, so I'm still suspecting your hardware, or your board initialization at this point.  There's ~zero that I can do from here I'm afraid.

**Comment by ravenland** [comment]
Thank you for the help so far @karlp. I managed to confirm that the hardware works, via another codebase. Will look further into this as time allows.

**Comment by karlp** [comment]
I'd check whether your board has external pull up control that  you might need to deal with?

**Comment by ravenland** [comment]
Found it, memcpy in usb_standard.c:76.

**Comment by karlp** [comment]
what does "found" mean for you?  I presume you're using some "special" toolchain then?  Or not building with the same compiler and linker flags as provided?

**Comment by ravenland** [comment]
arm-none-eabi-gcc -Os -Wall -Wextra -Wimplicit-function-declaration -Wredundant-decls -Wmissing-prototypes -Wstrict-prototypes -Wundef -Wshadow -I../../../include -fno-common -mcpu=cortex-m3  -mthumb -Wstrict-prototypes -ffunction-sections -fdata-sections -MD -DSTM32F1 -ggdb3 -std=c99  -o usb_standard.o -c ../../usb/usb_standard.c

arm-none-eabi-gcc (15:6.3.1+svn253039-1build1) 6.3.1 20170620

That is what unchanged lib make output.

In this case found means that the core hardfaults on that memcopy. It hardfaults because of an unaligned access. My first guess is that whatever toolchains make this work default to -mno-unaligned-access.

**Comment by ravenland** [comment]
The toolchain is the latest version in Ubuntu 18.4. It's not uncommon to see bugs in toolchains. Since arm-none-eabi is mentioned in the libopencm3 Readme.md maybe a "last known good" version would be helpful (I looked for one when this first started and couldn't find any).

I agree that the toolchain seems to be doing something wrong. When I have some more free time I'll look further into why this happens.

**Comment by ravenland** [comment]
I did a quick test, the arm toolchain works. The latest linaro bare metal doesn't.

**Comment by karlp** [comment]
ok, well, we can close this then.  glad you worked that out.
