### ISSUE TITLE
unrelated README.md

### ISSUE THREAD

**Issue by michalsykora** [libopencm3/libopencm3-examples#202]
Hi, i found unrelated readme file in this folder, probably forgotten copy paste. :)

https://github.com/libopencm3/libopencm3-examples/tree/master/examples/stm32/f3/stm32f3-discovery/i2c

Thanks for amazing work.

**Comment by karlp** [comment]
that's not unrelated, it's the readme for that particular example?  Unless I've misunderstood what you mean  by this, in which case feel free to re-open and comment further :)
