### ISSUE TITLE
stm32: FLASH_BASE only defined for F0/F1

### ISSUE THREAD

**Issue by matthijskooijman** [libopencm3/libopencm3-examples#224]
I'm working with a G0, and noticed that there doesn't seem to be a define for the flash base. Looking around, I see F0 and F1 define `FLASH_BASE`, but none of the other series.

Is there a particular reason for this? Maybe the address is chip-dependent rather than consistent across the series? Or is this just an oversight while adding support for the other series?

**Comment by karlp** [comment]
it's always 0x8000000 for all stm32, so far at least.  Feel free to add it to all the other stm32s if you really like, it's not a define most people ever see much use for.  I've written bootloaders on other targets and never even noticed it :)
