### ISSUE TITLE
A question about rfid driver

### ISSUE THREAD

**Issue by a495433** [libopencm3/libopencm3-examples#239]
I want to find an RFID demo that can run on stm32rct6. I haven't found it for a long time. This is my code warehouse https://github.com/justTestMind/stm32rct6 Can someone help me look at the problem? Thank you very much

**Comment by karlp** [comment]
This isn't really the place to ask for help with random projects, rather to track issues and bugs in the libopencm3 examples.

**Comment by a495433** [comment]
ok,thanks
