### ISSUE TITLE
Examples are difficult to find with much duplication

### ISSUE THREAD

**Issue by riban-bw** [libopencm3/libopencm3-examples#247]
This repository holds example code for various microprocessors, sorted by hardware / boards. This results in code that will run on a micropocessor being difficult to find because it is _hidden_ in a specific board's directory, e.g. CAN example for [obldc-strip](https://github.com/libopencm3/libopencm3-examples/tree/master/examples/stm32/f1/obldc-strip) may (with little adaptation) be run on Bluepill or other generic STM32F1 board.

The result is that finding examples often resorts to pefroming a Google search rather than browsing / searching the repro and code that is essentially the same is duplicated in different board directories. A user trying to find an example that demonstrates a function or on which to base their code needs to search for the examples, look at each one and decide which closest matches their board (often many match equally) before starting to understand and use the example.

It may be better to create examples directly below the processor identifier, e.g. `f0` with comment in the header / source / readme file that describes the specific platform(s) the example has been tested on. My current experience of the examples is that they are necessary, acting as a form of documentation for the lib (as only the API is doxygen documented) but challenging to use. This is especially true for newcomers to the library who need to understand how it works in various contexts. If their target platform is not well supported by (board specific) examples they have additional challenges to find related examples. (I have been designing for STM32F072 which has few examples.)

I know that changing the structure of the repro would be challenging but I feel that in its current form it is suboptimal and presents significant challenge (and hence friction) that is likely to discourage substantial quantity of potential users.

**Comment by karlp** [comment]
Correct, well understood, and exactly the reason taht this repository doesn't get further work.  For at least one of the purposes of this repository, to have working examples for various hardware to help test your toolchain and hardware, the https://github.com/libopencm3/libopencm3-miniblink provides a replacement.  For the API examples, it's open, but we're not keeping wishlist tickets open for things I'm afraid.
