### ISSUE TITLE
*.flash targets don't work with current openocd and miss references

### ISSUE THREAD

**Issue by karlp** [libopencm3/libopencm3-examples#34]
There's references to SCRIPT_DIR and stlink_flash.scr and so on, it's duplicated in the different stm32 directories, and some of the flash erase commands aren't correct for recent/current openocd releases

**Comment by quitte** [comment]
The flash helping snippets in the examples would be a nice addition to the mk directory

**Comment by karlp** [comment]
This appears to be mostly implemented now.
