### ISSUE TITLE
Multithreading example

### ISSUE THREAD

**Issue by prusnak** [libopencm3/libopencm3-examples#55]
I would love to see some examples for multithreading. Are there any? Is it possible to achieve this functionality without full-blown RTOS just with pure libopencm3?

**Comment by JonasNorling** [comment]
I had some context switching code from an old project. It's now cleaned up and baked into a pull request #98. I hope it can be of some help to someone.

**Comment by prusnak** [comment]
Closing in favor of https://github.com/libopencm3/libopencm3-examples/pull/98
