### ISSUE TITLE
stm32f429 usb cdc - can't seem to get example to work

### ISSUE THREAD

**Issue by anfractuosity** [libopencm3/libopencm3-examples#62]
Hi,

I can't seem to get /examples/stm32/f4/stm32f4-discovery/usb_cdcacm to
work under the stm32f429, it just doesn't seem to appear as a usb device
under lsusb.

Anyone got any ideas?

cheers

Chris

**Comment by schodet** [comment]
If you are using the discovery board, they used the USB OTG HS instead of the USB OTG FS, you just need to change the USB driver and GPIO configuration.

**Comment by karlp** [comment]
Closing this.  At the time of filing there was no specific f429 usb example in the repo, but it exists now.  There was confusion with the original f4 usb examples, which didn't work as is on f429 boards.
