### ISSUE TITLE
add notes no multiple source files to project reuse documentation

### ISSUE THREAD

**Issue by karlp** [libopencm3/libopencm3-examples#71]

**Comment by vitasam** [comment]
Any update on this?

**Comment by vitasam** [comment]
one of examles to have multiple sources:

-> Makefile
`SRC = hw.o usart.o`

-> libopencm3.rules.mk (next line after OBJS		+= $(BINARY).o)
`OBJS		+= $(SRC)`

**Comment by karlp** [comment]
this ticket is just to track that the notes on reusing the library should be updated, if you have a suggested edit to the documentation, please make it as a pull request.

**Comment by vitasam** [comment]
I made a pull request

**Comment by karlp** [comment]
I've updated the documentation based on your PR thanks, see 6bca6aa
