### ISSUE TITLE
Communicating arm-none-eabi-gcc location on windows

### ISSUE THREAD

**Issue by andrey-gvrd** [libopencm3/libopencm3-examples#87]
make in top level directory fails with this error:

    make[2]: arm-none-eabi-gcc: Command not found

arm-none-eabi-gcc.exe in my system is located at:

    C:\Program Files (x86)\GNU Tools ARM Embedded\4.9 2015q1\bin

I've tried running this command:

    export PATH="/c//Python27:/c//Program Files (x86)/GNU Tools ARM Embedded/4.9 2015q1/bin:/usr/local/bin:/usr/bin:/bin"

But it doesn't help. What am I doing wrong?

**Comment by ChuckM** [comment]
If you type simply `arm-none-eabi-gcc --version` on the command line what does it say?

**Comment by andrey-gvrd** [comment]
...

    arm-none-eabi-gcc: command not found

**Comment by andrey-gvrd** [comment]
I've reinstalled it to a folder which contains no space characters and that part now works.

**Comment by andrey-gvrd** [comment]
I believe I'm still stuck on the same issue. 

Even though `arm-none-eabi-gcc --version` now returns `arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 4.9.3 20150303 (release) [ARM/embedded-4_9-branch revision 221220]`, make now fails with `flash.d:1: *** multiple target patterns.  Stop.`

I've tried setting paths this way:

     export PATH="/cygwin/c/Python27:/cygwin/c/ARMToolchain/bin:/usr/local/bin:/usr/bin:/bin"

But it didn't work.

**Comment by ChuckM** [comment]
Can you pop over to the #libopencm3 channel on irc.freenode.net ?

**Comment by karlp** [comment]
Is there anything real here to work on? Was this resolved?

**Comment by andrey-gvrd** [comment]
I think I settled on the fact that I have to use linux to make this work. So yeah, issue's done.
