### ISSUE TITLE
f3 busy loop before inital usbd poll

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3-examples#97]
https://github.com/libopencm3/libopencm3-examples/blob/master/examples/stm32/f3/stm32f3-discovery/usb_cdcacm/cdcacm.c#L261

what is the use?

**Comment by karlp** [comment]
Presumably this was working around one of the old bugs in control setups.  It's been dropped and the example udpated to use a proper clock. thanks for the report
